providers = ["java"]

[variables]
NIXPACKS_JDK_VERSION = "17"

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -Dserver.address=0.0.0.0 -jar target/ShopSphere-0.0.1-SNAPSHOT.war"
